### ISSUE TITLE
Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by adultmovieactor** [forkyyy/http-browser-v2#1]
![image](https://user-images.githubusercontent.com/104075270/166315983-f55f7683-4b6c-4edf-8b06-f1f262d66dbe.png)

**Comment by iLaravel** [comment]
Hi bro, try: 


sudo apt-get install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 \
libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \
ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget -y

**Comment by bestrayni** [comment]
have the same problem

**Comment by adultmovieactor** [comment]
> Hi bro, try:
> 
> sudo apt-get install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget -y
![image](https://user-images.githubusercontent.com/104075270/166688282-f9d491a1-e0d0-4c97-95fa-fec85e8f1eb2.png)
you know anything about that?

**Comment by iLaravel** [comment]
Its just bad proxy

**Comment by bestrayni** [comment]
Now it's working fine

**Comment by adultmovieactor** [comment]
> Its just bad proxy

recommend me any good proxy providers?
any price.

**Comment by adultmovieactor** [comment]
and btw its getting cookies but still not sending requests...
